name: tbp-parser pytests
on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: "2.3.2"
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached dependencies
        id: cached_dependencies
        uses: actions/cache@v5
        with:
          path: .venv
          key: venv-${{ runner.os }}-tbp-parser-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        if: steps.cached_dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction

      - name: Run pytest-cov
        run: poetry run pytest --cov -vv