name: Test WIP Auth

on:
  push:
    branches:
      - al-gha-test
      
permissions:
  contents: read
  id-token: write

jobs:
  test-auth:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v3
        with:
          project_id: general-theiagen
          workload_identity_provider: ${{ secrets.WIP_PROVIDER }}

      - name: Verify auth
        run: gcloud auth application-default print-access-token
